#!/usr/bin/env bash

file="sample.s"
if [[ -f $file ]]; then
  rm $file
fi
touch $file
echo "----- asm -----"
while read line; do
  echo "$line"
  echo "$line" >> $file
done
gcc $file
echo "----- result -----"
./a.out
echo $?

exit 0

